version: "3.7"

services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - .env
  backend:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
volumes:
  bundle_data: