default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
development:
  <<: *default
  database: <%= "#{ENV["POSTGRES_DB"]}_development"%>
  host: <%= ENV["RAILS_DB_HOST"] %>
test:
  <<: *default
  host: <%= ENV["RAILS_DB_HOST"] %>
  database: <%= "#{ENV["POSTGRES_DB"]}_development"%>
production:
  <<: *default
  database: <%= "#{ENV["POSTGRES_DB"]}"%>
